#
# Example .tmux.conf
#
# By Nicholas Marriott. Public domain.
#

# Some tweaks to the status line
set -g status-right "%H:%M"
set -g window-status-current-style "underscore"


# If running inside tmux ($TMUX is set), then change the status line to red

%if #{TMUX}
set -g status-bg red
%endif


set -s set-clipboard on         #osc 52 copy paste share with iterm

bind-key P display-popup -E -w 85% -h 85% -d '#{pane_current_path}' bash

# 水平分割（上下）时自动继承当前路径
bind '"' split-window -v -c "#{pane_current_path}"

# 垂直分割（左右）时自动继承当前路径
bind '%' split-window -h -c "#{pane_current_path}"



# display cpu and memory
set -g status-interval 1
set -g status-right-length 120
set -g status-right '#{cpu_bg_color} CPU #{cpu_percentage} #{ram_bg_color} #(/root/Dotfile/tmux/scripts/ram_status.sh) #[default]'

set -g @cpu_percentage_format "%3.1f%%"


# Turn the mouse on, but without copy mode dragging
set -g mouse on



set -gq allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-cpu'

run '~/.config/tmux/plugins/tpm/tpm'
